Repository datajoint/datajoint-labbook, pull requests merged in 2021-03, with the labels that each got.

#105 delete date/time format conversion fix, update primary field css
  CHANGELOG.md
  src/Components/MainTableView/DataStorageClasses/TableAttribute.tsx
  src/Components/MainTableView/DeleteTuple/DeleteTuple.tsx
  src/Components/MainTableView/UpdateTuple/UpdateTuple.css
  src/Components/MainTableView/UpdateTuple/UpdateTuple.tsx
Labels: bug

#106 Datetime bug with dealing with undefined values
  CHANGELOG.md
  src/Components/MainTableView/DataStorageClasses/TableAttribute.tsx
Labels: bug, high-priority

#117 Pageination rewrite
  CHANGELOG.md
  src/Components/MainTableView/DataStorageClasses/TableAttribute.tsx
  src/Components/MainTableView/Filter/Filter.tsx
  src/Components/MainTableView/TableContent.css
  src/Components/MainTableView/TableContent.tsx
  src/Components/MainTableView/TableInfo.tsx
  src/Components/MainTableView/TableView.css
  src/Components/MainTableView/TableView.tsx
  src/Components/SideMenu/TableList.tsx
Labels: enhancement, high-priority

#118 Update lables according to feed back
  CHANGELOG.md
  src/Components/MainTableView/DataStorageClasses/TableAttribute.tsx
Labels: enhancement

#124 Add doc string for type docs
  CHANGELOG.md
  src/Components/App.tsx
  src/Components/Home.tsx
  src/Components/LoadingAnimation/BasicLoadingIcon.tsx
  src/Components/LoadingAnimation/TableListLoading.tsx
  src/Components/Login.tsx
  src/Components/MainTableView/CheckDependency.css
  src/Components/MainTableView/CheckDependency.tsx
  src/Components/MainTableView/DataStorageClasses/PrimaryTableAttribute.tsx
  src/Components/MainTableView/DataStorageClasses/Restriction.tsx
  src/Components/MainTableView/DataStorageClasses/SecondaryTableAttribute.tsx
  src/Components/MainTableView/DataStorageClasses/TableAttribute.tsx
  src/Components/MainTableView/DataStorageClasses/TableAttributesInfo.tsx
  src/Components/MainTableView/DeleteTuple/DeleteTuple.tsx
  src/Components/MainTableView/Filter/Filter.tsx
  src/Components/MainTableView/Filter/FilterCard.tsx
  src/Components/MainTableView/InsertTuple/InsertTuple.tsx
  src/Components/MainTableView/TableContent.tsx
  src/Components/MainTableView/TableInfo.tsx
  src/Components/MainTableView/TableView.tsx
  src/Components/MainTableView/UpdateTuple/UpdateTuple.tsx
  src/Components/NavBar.tsx
  src/Components/SideMenu/SchemaList.tsx
  src/Components/SideMenu/SideMenu.tsx
  src/Components/SideMenu/TableList.tsx
  src/Components/SideMenu/TableListDict.tsx
  src/index.tsx
Labels: documentation, enhancement, high-priority

#135 Disable Default button, added ability to insret nullable blobs, serval other bugs fixes
  CHANGELOG.md
  src/Components/App.css
  src/Components/Home.css
  src/Components/MainTableView/DataStorageClasses/SecondaryTableAttribute.tsx
  src/Components/MainTableView/DataStorageClasses/TableAttribute.tsx
  src/Components/MainTableView/Filter/Filter.tsx
  src/Components/MainTableView/InsertTuple/InsertTuple.tsx
  src/Components/MainTableView/TableContent.css
  src/Components/MainTableView/TableContent.tsx
  src/Components/MainTableView/TableView.css
  src/Components/MainTableView/TableView.tsx
  src/Components/MainTableView/UpdateTuple/UpdateTuple.tsx
  src/Components/SideMenu/SideMenu.css
Labels: bug, enhancement, high-priority
