Repository datajoint/datajoint-labbook, pull requests merged in 2021-02, with the labels that each got.

#45 Change PartTable name handling
  src/Components/SideMenu/TableList.tsx
Labels: bug, enhancement

#46 add copy over for insert, temporary loading message
  src/Components/MainTableView/InsertTuple.css
  src/Components/MainTableView/InsertTuple.tsx
  src/Components/MainTableView/TableContent.tsx
  src/Components/MainTableView/TableView.css
  src/Components/MainTableView/TableView.tsx
Labels: enhancement

#51 Added filter support
  src/Components/MainTableView/DataStorageClasses/Restriction.tsx
  src/Components/MainTableView/DataStorageClasses/TableAttribute.tsx
  src/Components/MainTableView/Filter/Filter.css
  src/Components/MainTableView/Filter/Filter.tsx
  src/Components/MainTableView/Filter/FilterCard.css
  src/Components/MainTableView/Filter/FilterCard.tsx
  src/Components/MainTableView/InsertTuple.tsx
  src/Components/MainTableView/TableContent.tsx
  src/Components/MainTableView/TableView.tsx
  src/Components/MainTableView/enums/RestrictionType.tsx
  src/Components/NavBar.tsx
Labels: enhancement

#59 Added search functioailty to schema list
  src/Components/SideMenu/SchemaList.tsx
  src/Components/SideMenu/SideMenu.tsx
Labels: enhancement

#60 Add version number
  package.json
  src/Components/Login.tsx
  src/Components/MainTableView/TableView.tsx
  src/Components/NavBar.css
  src/Components/NavBar.tsx
Labels: enhancement

#86 Added support for decimal and partially rewrote insert and update form generation code.
  CHANGELOG.md
  README.md
  src/Components/App.css
  src/Components/MainTableView/DataStorageClasses/PrimaryTableAttribute.tsx
  src/Components/MainTableView/DataStorageClasses/SecondaryTableAttribute.tsx
  src/Components/MainTableView/DataStorageClasses/TableAttribute.tsx
  src/Components/MainTableView/DeleteTuple/DeleteTuple.css
  src/Components/MainTableView/DeleteTuple/DeleteTuple.tsx
  src/Components/MainTableView/InsertTuple.css
  src/Components/MainTableView/InsertTuple.tsx
  src/Components/MainTableView/InsertTuple/InsertTuple.css
  src/Components/MainTableView/InsertTuple/InsertTuple.tsx
  src/Components/MainTableView/TableContent.tsx
  src/Components/MainTableView/TableView.css
  src/Components/MainTableView/TableView.tsx
  src/Components/MainTableView/UpdateTuple.css
  src/Components/MainTableView/UpdateTuple.tsx
  src/Components/MainTableView/UpdateTuple/UpdateTuple.css
  src/Components/MainTableView/UpdateTuple/UpdateTuple.tsx
  src/Components/MainTableView/enums/TableAttributeType.tsx
  src/Components/NavBar.tsx
Labels: bug, enhancement

#90 Fix parameters being in the wrong order.
  src/Components/MainTableView/Filter/FilterCard.tsx
Labels: bug

#88 Table search
  CHANGELOG.md
  src/Components/MainTableView/CheckDependency.tsx
  src/Components/MainTableView/TableView.tsx
  src/Components/MainTableView/UpdateTuple/UpdateTuple.tsx
  src/Components/SideMenu/SideMenu.css
  src/Components/SideMenu/TableList.css
  src/Components/SideMenu/TableList.tsx
Labels: enhancement

#89 Fixed issue with null not displaying correctly for time, datetime, and timestamp
  CHANGELOG.md
  src/Components/MainTableView/DataStorageClasses/TableAttribute.tsx
Labels: enhancement
